import type { ProjectPreset } from '@core/store/createProjectStore';
import type { DysonConfig } from './config';

/**
 * Presets spell out every field rather than relying on the current value. A
 * preset is a whole look here — leaving, say, `beamCount` at whatever the last
 * preset set would make "Blueprint" arrive with lances still firing.
 */
export const PRESETS: ProjectPreset<DysonConfig>[] = [
  {
    // The house look: violet trusses, a blue-white tap, warm accent detailing.
    name: 'Aurora Bloom',
    config: {
      structureRadius: 0.26,
      hexSize: 0.09,
      panelDensity: 0.78,
      panelEmission: 0.6,
      emissionScale: 0.45,
      coreIntensity: 0.55,
      coreColor: '#9AD5FF',
      structureColor: '#8A7CF0',
      accentColor: '#FFC66B',
      ringCount: 4,
      ringWidth: 0.055,
      ringInclination: 0.55,
      ringSpread: 0.5,
      showSpurs: true,
      finCount: 9,
      beamCount: 2,
      debrisDensity: 0.5,
      starDensity: 0.5,
      nebulaStrength: 0.45,
      showGraticule: true,
      showBrackets: true,
      showDataBlock: true,
      vignette: 0.45,
    },
  },
  {
    // A red giant part-way through enclosure: huge, sparse, still being plated.
    name: 'Ember Giant',
    config: {
      structureRadius: 0.31,
      hexSize: 0.115,
      panelDensity: 0.52,
      panelEmission: 0.85,
      emissionScale: 0.7,
      coreIntensity: 0.85,
      coreColor: '#FF9C6B',
      structureColor: '#C77B5F',
      accentColor: '#FFE0A3',
      ringCount: 3,
      ringWidth: 0.075,
      ringInclination: 0.35,
      ringSpread: 0.65,
      showSpurs: true,
      finCount: 12,
      beamCount: 2,
      debrisDensity: 0.75,
      starDensity: 0.35,
      nebulaStrength: 0.7,
      showGraticule: false,
      showBrackets: true,
      showDataBlock: true,
      vignette: 0.6,
    },
  },
  {
    // Finished, cold and clinical. Fine plating, tight trusses, no swarm left.
    name: 'Glacier Array',
    config: {
      structureRadius: 0.23,
      hexSize: 0.055,
      panelDensity: 0.97,
      panelEmission: 0.35,
      emissionScale: 0.28,
      coreIntensity: 0.4,
      coreColor: '#E8F6FF',
      structureColor: '#7FA0B8',
      accentColor: '#6BE8FF',
      ringCount: 6,
      ringWidth: 0.035,
      ringInclination: 0.75,
      ringSpread: 0.25,
      showSpurs: false,
      finCount: 6,
      beamCount: 1,
      debrisDensity: 0.18,
      starDensity: 0.75,
      nebulaStrength: 0.2,
      showGraticule: true,
      showBrackets: true,
      showDataBlock: true,
      vignette: 0.3,
    },
  },
  {
    // Drafting-table variant: near-monochrome, all furniture on, nothing glowing
    // hard enough to distract from the geometry.
    name: 'Blueprint',
    config: {
      structureRadius: 0.27,
      hexSize: 0.075,
      panelDensity: 0.86,
      panelEmission: 0.22,
      emissionScale: 0.35,
      coreIntensity: 0.3,
      coreColor: '#BFD8E8',
      structureColor: '#5FA8C7',
      accentColor: '#FFFFFF',
      ringCount: 5,
      ringWidth: 0.04,
      ringInclination: 0.6,
      ringSpread: 0.35,
      showSpurs: true,
      finCount: 10,
      beamCount: 0,
      debrisDensity: 0.35,
      starDensity: 0.25,
      nebulaStrength: 0.12,
      showGraticule: true,
      showBrackets: true,
      showDataBlock: true,
      vignette: 0.25,
    },
  },
  {
    // Something went wrong here. Acid core, magenta detailing, half the shell
    // missing and every emitter lit.
    name: 'Verdigris Fault',
    config: {
      structureRadius: 0.29,
      hexSize: 0.13,
      panelDensity: 0.44,
      panelEmission: 0.95,
      emissionScale: 0.85,
      coreIntensity: 0.9,
      coreColor: '#C9FF8F',
      structureColor: '#9E6FD6',
      accentColor: '#FF6B8A',
      ringCount: 2,
      ringWidth: 0.085,
      ringInclination: 0.2,
      ringSpread: 0.9,
      showSpurs: true,
      finCount: 14,
      beamCount: 4,
      debrisDensity: 0.9,
      starDensity: 0.6,
      nebulaStrength: 0.8,
      showGraticule: false,
      showBrackets: false,
      showDataBlock: true,
      vignette: 0.55,
    },
  },
];
