import type { ProjectPreset } from '@core/store/createProjectStore';
import type { StarchartConfig } from './config';

/**
 * Presets are Partial, so a field left out keeps whatever was there. Every field
 * that would look wrong carried over from another preset is spelled out — which,
 * for a plate whose whole identity is its palette and density, is all of them.
 */
export const PRESETS: ProjectPreset<StarchartConfig>[] = [
  {
    name: 'Void Atlas',
    config: {
      theme: 'void',
      accentColor: '#6FD3FF',
      grain: 0.3,
      hazeStrength: 0.58,
      hazeCurve: 0.35,
      starDensity: 1,
      starBloom: 0.6,
      spectralTint: 0.35,
      showGraticule: true,
      graticuleOpacity: 0.5,
      secondaryProjection: true,
      showConstellations: true,
      constellationCount: 16,
      showRoutes: true,
      routeDensity: 0.5,
      showLabels: true,
      labelDensity: 0.55,
      showCallouts: true,
      showInsets: true,
      showFrame: true,
      showTitleBlock: true,
      margin: 0.045,
    },
  },
  {
    // CRT phosphor: one hue throughout, heavy grain, grid pushed forward.
    name: 'Phosphor',
    config: {
      theme: 'amber',
      accentColor: '#FF8A3D',
      grain: 0.62,
      hazeStrength: 0.44,
      hazeCurve: -0.25,
      starDensity: 0.85,
      starBloom: 0.85,
      spectralTint: 0.08,
      showGraticule: true,
      graticuleOpacity: 0.78,
      secondaryProjection: false,
      showConstellations: true,
      constellationCount: 12,
      showRoutes: true,
      routeDensity: 0.66,
      showLabels: true,
      labelDensity: 0.7,
      showCallouts: true,
      showInsets: false,
      showFrame: true,
      showTitleBlock: true,
      margin: 0.05,
    },
  },
  {
    // Naval chart: heavy plate furniture, restrained field, routes in the lead.
    name: 'Naval Chart',
    config: {
      theme: 'naval',
      accentColor: '#7FE3C0',
      grain: 0.2,
      hazeStrength: 0.34,
      hazeCurve: 0.62,
      starDensity: 0.7,
      starBloom: 0.42,
      spectralTint: 0.15,
      showGraticule: true,
      graticuleOpacity: 0.66,
      secondaryProjection: true,
      showConstellations: false,
      constellationCount: 22,
      showRoutes: true,
      routeDensity: 0.82,
      showLabels: true,
      labelDensity: 0.75,
      showCallouts: true,
      showInsets: true,
      showFrame: true,
      showTitleBlock: true,
      margin: 0.055,
    },
  },
  {
    // Dark ink on cream stock. Bloom drops to near nothing — a glow on paper
    // reads as a smudge, not a star.
    name: 'Printed Plate',
    config: {
      theme: 'plate',
      accentColor: '#A03A2A',
      grain: 0.7,
      hazeStrength: 0.4,
      hazeCurve: -0.5,
      starDensity: 0.8,
      starBloom: 0.12,
      spectralTint: 0.2,
      showGraticule: true,
      graticuleOpacity: 0.85,
      secondaryProjection: false,
      showConstellations: true,
      constellationCount: 22,
      showRoutes: true,
      routeDensity: 0.4,
      showLabels: true,
      labelDensity: 0.85,
      showCallouts: true,
      showInsets: true,
      showFrame: true,
      showTitleBlock: true,
      margin: 0.06,
    },
  },
  {
    // Everything turned up: the busy survey exposure.
    name: 'Deep Survey',
    config: {
      theme: 'survey',
      accentColor: '#FF5F7E',
      grain: 0.18,
      hazeStrength: 0.86,
      hazeCurve: 0.15,
      starDensity: 2.1,
      starBloom: 0.75,
      spectralTint: 0.6,
      showGraticule: true,
      graticuleOpacity: 0.32,
      secondaryProjection: true,
      showConstellations: true,
      constellationCount: 28,
      showRoutes: true,
      routeDensity: 0.92,
      showLabels: true,
      labelDensity: 0.95,
      showCallouts: true,
      showInsets: true,
      showFrame: true,
      showTitleBlock: true,
      margin: 0.035,
    },
  },
];
