import type { ProjectPreset } from '@core/store/createProjectStore';
import type { StarchartConfig } from './config';

/**
 * Presets are Partial, so a field left out keeps whatever was there. Every field
 * that would look wrong carried over from another preset is spelled out — which,
 * for a plate whose identity is its palette, its pointing and its depth, is all
 * of them.
 *
 * Each one points at a real piece of sky, and the field of view is chosen to
 * frame that subject rather than to hit a number.
 */
export const PRESETS: ProjectPreset<StarchartConfig>[] = [
  {
    // Orion: the most legible figure in the sky, and the plate that most
    // obviously proves the stars are real.
    name: 'Orion',
    config: {
      raCenter: 83.5,
      decCenter: 0,
      roll: 0,
      fieldOfView: 48,
      projection: 'stereographic',
      limitingMag: 7.4,
      theme: 'void',
      accentColor: '#6FD3FF',
      grain: 0.3,
      hazeStrength: 0.58,
      starBloom: 0.6,
      spectralTint: 0.5,
      showGraticule: true,
      graticuleOpacity: 0.5,
      galacticGrid: true,
      showConstellations: true,
      constellationLabels: true,
      showRoutes: true,
      routeDensity: 0.5,
      showLabels: true,
      labelDensity: 0.55,
      showCallouts: true,
      showInsets: true,
      showFrame: true,
      showTitleBlock: true,
      margin: 0.045,
    },
  },
  {
    // The galactic centre in Sagittarius: the densest, haziest field there is, so
    // the plate goes deep and lets the Milky Way carry it.
    name: 'Galactic Core',
    config: {
      raCenter: 266.4,
      decCenter: -28.9,
      roll: 0,
      fieldOfView: 62,
      projection: 'equalArea',
      limitingMag: 8,
      theme: 'survey',
      accentColor: '#FF5F7E',
      grain: 0.18,
      hazeStrength: 0.9,
      starBloom: 0.7,
      spectralTint: 0.62,
      showGraticule: true,
      graticuleOpacity: 0.32,
      galacticGrid: true,
      showConstellations: true,
      constellationLabels: false,
      showRoutes: true,
      routeDensity: 0.92,
      showLabels: true,
      labelDensity: 0.9,
      showCallouts: true,
      showInsets: true,
      showFrame: true,
      showTitleBlock: true,
      margin: 0.035,
    },
  },
  {
    // CRT phosphor over the Cygnus rift: one hue throughout, heavy grain, grid
    // pushed forward, and a shallow cut so the field stays readable.
    name: 'Phosphor',
    config: {
      raCenter: 310,
      decCenter: 42,
      roll: -8,
      fieldOfView: 44,
      projection: 'gnomonic',
      limitingMag: 6.4,
      theme: 'amber',
      accentColor: '#FF8A3D',
      grain: 0.62,
      hazeStrength: 0.5,
      starBloom: 0.85,
      spectralTint: 0.1,
      showGraticule: true,
      graticuleOpacity: 0.78,
      galacticGrid: false,
      showConstellations: true,
      constellationLabels: true,
      showRoutes: true,
      routeDensity: 0.66,
      showLabels: true,
      labelDensity: 0.7,
      showCallouts: true,
      showInsets: false,
      showFrame: true,
      showTitleBlock: true,
      margin: 0.05,
    },
  },
  {
    // Naval chart over Crux and Carina: heavy plate furniture, restrained field,
    // routes in the lead. The southern sky no northern chart ever carried.
    name: 'Southern Naval',
    config: {
      raCenter: 175,
      decCenter: -60,
      roll: 12,
      fieldOfView: 58,
      projection: 'equidistant',
      limitingMag: 6.8,
      theme: 'naval',
      accentColor: '#7FE3C0',
      grain: 0.2,
      hazeStrength: 0.42,
      starBloom: 0.42,
      spectralTint: 0.25,
      showGraticule: true,
      graticuleOpacity: 0.66,
      galacticGrid: true,
      showConstellations: false,
      constellationLabels: false,
      showRoutes: true,
      routeDensity: 0.82,
      showLabels: true,
      labelDensity: 0.75,
      showCallouts: true,
      showInsets: true,
      showFrame: true,
      showTitleBlock: true,
      margin: 0.055,
    },
  },
  {
    // Dark ink on cream stock over Ursa Major. Bloom drops to near nothing — a
    // glow on paper reads as a smudge, not a star — and the cut is shallow,
    // because a letterpress plate could never hold magnitude 8.
    name: 'Printed Plate',
    config: {
      raCenter: 175,
      decCenter: 55,
      roll: 0,
      fieldOfView: 62,
      projection: 'stereographic',
      limitingMag: 5.8,
      theme: 'plate',
      accentColor: '#A03A2A',
      grain: 0.7,
      hazeStrength: 0.36,
      starBloom: 0.12,
      spectralTint: 0.2,
      showGraticule: true,
      graticuleOpacity: 0.85,
      galacticGrid: false,
      showConstellations: true,
      constellationLabels: true,
      showRoutes: true,
      routeDensity: 0.4,
      showLabels: true,
      labelDensity: 0.85,
      showCallouts: true,
      showInsets: true,
      showFrame: true,
      showTitleBlock: true,
      margin: 0.06,
    },
  },
  {
    // The Pleiades at close range: a narrow field, everything else stripped back
    // so the cluster is the whole plate.
    name: 'Pleiades Detail',
    config: {
      raCenter: 56.75,
      decCenter: 24.1,
      roll: 0,
      fieldOfView: 22,
      projection: 'gnomonic',
      limitingMag: 8,
      theme: 'void',
      accentColor: '#B98CFF',
      grain: 0.25,
      hazeStrength: 0.3,
      starBloom: 0.8,
      spectralTint: 0.7,
      showGraticule: true,
      graticuleOpacity: 0.35,
      galacticGrid: false,
      showConstellations: true,
      constellationLabels: false,
      showRoutes: false,
      routeDensity: 0.3,
      showLabels: true,
      labelDensity: 0.85,
      showCallouts: true,
      showInsets: true,
      showFrame: true,
      showTitleBlock: true,
      margin: 0.05,
    },
  },
];
